delete from VICE_PRESIDENT;

insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('George Washington', 'John Adams', 1789, 1797);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('John Adams', 'Thomas Jefferson', 1797, 1801);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Thomas Jefferson', 'Aaron Burr', 1801, 1805);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Thomas Jefferson', 'George Clinton', 1805, 1809);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('James Madison', 'George Clinton', 1809, 1812);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('James Madison', 'None', 1812, 1813);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('James Madison', 'Elbridge Gerry', 1813, 1814);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('James Madison', 'None', 1814, 1817);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('James Monroe', 'Daniel D. Tompkins', 1817, 1825);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('John Quincy', 'John C. Calhoun', 1825, 1829);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Andrew Jackson', 'John C. Calhoun', 1829, 1832);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Andrew Jackson', 'None', 1832, 1833);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Andrew Jackson', 'Martin Van', 1833, 1837);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Martin Van', 'Richard M. Johnson', 1837, 1841);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('William Henry', 'John Tyler', 1841, 0);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('John Tyler', 'None', 1841, 1845);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('James K. Polk', 'George M. Dallas', 1845, 1849);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Zachary Taylor', 'Millard Fillmore', 1849, 1850);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Millard Fillmore', 'None', 1850, 1853);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Franklin Pierce', 'William King', 1853, 0);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Franklin Pierce', 'None', 1853, 1857);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('James Buchanan', 'John C. Breckinridge', 1857, 1861);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Abraham Lincoln', 'Hannibal Hamlin', 1861, 1865);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Abraham Lincoln', 'Andrew Johnson', 1865, 0);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Andrew Johnson', 'None', 1865, 1869);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Ulysses S. Grant', 'Schuyler Colfax', 1869, 1873);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Ulysses S. Grant', 'Henry Wilson', 1873, 1875);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Ulysses S. Grant', 'None', 1875, 1877);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Rutherford B. Hayes', 'William Wheeler', 1877, 1881);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('James A. Garfield', 'Chester Arthur', 1881, 0);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Chester Arthur', 'None', 1881, 1885);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Grover Cleveland', 'Thomas Hendricks', 1885, 0);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Grover Cleveland', 'None', 1885, 1889);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Benjamin Harrison', 'Levi P. Morton', 1889, 1893);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Grover Cleveland', 'Adlai E. Stevenson', 1893, 1897);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('William McKinley', 'Garret Hobart', 1897, 1899);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('William McKinley', 'None', 1899, 1901);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('William McKinley', 'Theodore Roosevelt', 1901, 0);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Theodore Roosevelt', 'None', 1901, 1905);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Theodore Roosevelt', 'Charles Fairbanks', 1905, 1909);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('William Howard', 'James S. Sherman', 1909, 1912);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('William Howard', 'None', 1912, 1913);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Woodrow Wilson', 'Thomas R. Marshall', 1913, 1921);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Warren G. Harding', 'Calvin Coolidge', 1921, 1923);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Calvin Coolidge', 'None', 1923, 1925);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Calvin Coolidge', 'Charles Dawes', 1925, 1929);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Herbert Hoover', 'Charles Curtis', 1929, 1933);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Franklin D. Roosevelt', 'John Nance', 1933, 1941);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Franklin D. Roosevelt', 'Henry A. Wallace', 1941, 1945);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Franklin D. Roosevelt', 'Harry S. Truman', 1945, 0);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Harry S. Truman', 'None', 1945, 1949);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Harry S. Truman', 'Alben Barkley', 1949, 1953);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Dwight D. Eisenhower', 'Richard Nixon', 1953, 1961);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('John F. Kennedy', 'Lyndon B. Johnson', 1961, 1963);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Lyndon B. Johnson', 'None', 1963, 1965);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Lyndon B. Johnson', 'Hubert Humphrey', 1965, 1969);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Richard Nixon', 'Spiro Agnew', 1969, 1973);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Richard Nixon', 'None', 1973, 0);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Richard Nixon', 'Gerald Ford', 1973, 1974);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Gerald Ford', 'None', 1974, 0);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Gerald Ford', 'Nelson Rockefeller', 1974, 1977);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Jimmy Carter', 'Walter Mondale', 1977, 1981);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Ronald Reagan', 'George Bush', 1981, 1989);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('George Bush', 'Dan Quayle', 1989, 1993);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Bill Clinton', 'Al Gore', 1993, 2001);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('George W. Bush', 'Dick Cheney', 2001, 2009);
insert into db.VICE_PRESIDENT (pName, vName, StartYear, EndYear) values ('Barack Obama', 'Joe Biden', 2009, 2016);

select * from VICE_PRESIDENT;