delete from db.PRESIDENT;

insert into db.PRESIDENT (Name, StartYear, EndYear) values ('George Washington', 1789, 1793);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('George Washington', 1792, 1796);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('John Adams', 1796, 1800);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('Thomas Jefferson', 1800, 1804);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('Thomas Jefferson', 1804, 1808);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('James Madison', 1808, 1812);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('James Madison', 1812, 1816);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('James Monroe', 1816, 1820);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('James Monroe', 1820, 1824);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('JOHN Q. ADAMS', 1824, 1828);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('ANDREW JACKSON', 1828, 1832);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('ANDREW JACKSON', 1832, 1836);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('MARTIN VAN BUREN', 1836, 1840);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('WILLIAM H. HARRISON', 1840, 1844);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('JAMES K. POLK', 1844, 1848);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('ZACHARY TAYLOR', 1848, 1852);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('FRANKLIN PIERCE', 1852, 1856);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('JAMES BUCHANAN', 1856, 1860);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('ABRAHAM LINCOLN', 1860, 1864);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('ABRAHAM LINCOLN', 1864, 1868);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('ULYSSES S. GRANT', 1868, 1872);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('ULYSSES S. GRANT', 1872, 1876);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('RUTHERFORD B. HAYES', 1876, 1880);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('JAMES A. GARFIELD', 1880, 1884);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('GROVER CLEVELAND', 1884, 1888);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('BENJAMIN HARRISON', 1888, 1892);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('GROVER CLEVELAND', 1892, 1896);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('WILLIAM McKINLEY', 1896, 1900);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('WILLIAM McKINLEY', 1900, 1904);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('THEODORE ROOSEVELT', 1904, 1908);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('WILLIAM H. TAFT', 1908, 1912);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('WOODROW WILSON', 1912, 1916);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('WOODROW WILSON', 1916, 1920);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('WARREN G. HARDING', 1920, 1924);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('CALVIN COOLIDGE', 1924, 1928);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('HERBERT HOOVER', 1928, 1932);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('FRANKLIN D. ROOSEVELT', 1932, 1936);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('FRANKLIN D. ROOSEVELT', 1936, 1940);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('FRANKLIN D. ROOSEVELT', 1940, 1944);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('FRANKLIN D. ROOSEVELT', 1944, 1948);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('HARRY S TRUMAN', 1948, 1952);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('DWIGHT D. EISENHOWER', 1952, 1956);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('DWIGHT D. EISENHOWER', 1956, 1960);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('JOHN F. KENNEDY', 1960, 1964);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('LYNDON B. JOHNSON', 1964, 1968);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('RICHARD M. NIXON', 1968, 1972);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('RICHARD M. NIXON', 1972, 1976);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('JIMMY CARTER', 1976, 1980);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('RONALD REAGAN', 1980, 1984);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('RONALD REAGAN', 1984, 1988);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('GEORGE BUSH', 1988, 1992);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('BILL CLINTON', 1992, 1996);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('BILL CLINTON', 1996, 2000);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('GEORGE W. BUSH', 2000, 2004);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('GEORGE W. BUSH', 2004, 2008);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('BARACK OBAMA', 2008, 2012);
insert into db.PRESIDENT (Name, StartYear, EndYear) values ('BARACK OBAMA', 2012, 2016);

select * from db.PRESIDENT;