delete from db.RUNNING_MATE;

insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Donald Trump', 'Mike Pence', 2016, 2020);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Hillary Clinton', 'Tim Kaine', 2016, 2020);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Barack Obama', 'Joe Biden', 2012, 2016);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Mitt Romney', 'Paul Ryan', 2012, 2016);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Barack Obama', 'Joe Biden', 2008, 2012);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John McCain', 'Sarah Palin', 2008, 2012);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('George W. Bush', 'Dick Cheney', 2004, 2008);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John Kerry', 'John Edwards', 2004, 2008);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('George W. Bush', 'Dick Cheney', 2000, 2004);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Al Gore', 'Joe Lieberman', 2000, 2004);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Bill Clinton', 'Al Gore', 1996, 2000);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Bob Dole', 'Jack Kemp', 1996, 2000);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Bill Clinton', 'Al Gore', 1992, 1996);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('George H.W. Bush', 'Dan Quayle', 1992, 1996);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Ross Perot', 'James Stockdale', 1992, 1996);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('George H.W. Bush', 'Dan Quayle', 1988, 1992);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Michael Dukakis', 'Lloyd Bentsen', 1988, 1992);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Ronald Reagan', 'George H.W. Bush', 1984, 1988);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Walter Mondale', 'Geraldine Ferraro', 1984, 1988);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Ronald Reagan', 'George H.W. Bush', 1980, 1984);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Jimmy Carter', 'Walter Mondale', 1980, 1984);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Jimmy Carter', 'Walter Mondale', 1976, 1980);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Gerald Ford', 'Bob Dole', 1976, 1980);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Richard Nixon', 'Spiro Agnew', 1972, 1976);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('George McGovern', 'Sargent Shriver', 1972, 1976);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Richard Nixon', 'Spiro Agnew', 1968, 1972);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Hubert Humphrey', 'Edmund Muskie', 1968, 1972);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('George Wallace', 'Curtis LeMay', 1968, 1972);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Lyndon Johnson', 'Hubert Humphrey', 1964, 1968);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Barry Goldwater', 'William E. Miller', 1964, 1968);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John F. Kennedy', 'Lyndon Johnson', 1960, 1964);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Richard Nixon', 'Henry Cabot Lodge Jr.', 1960, 1964);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Dwight Eisenhower', 'Richard Nixon', 1956, 1960);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Adlai Stevenson II', 'Estes Kefauver', 1956, 1960);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Dwight Eisenhower', 'Richard Nixon', 1952, 1956);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Adlai Stevenson II', 'John Sparkman', 1952, 1956);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Harry Truman', 'Alben Barkley', 1948, 1952);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Thomas E. Dewey', 'Earl Warren', 1948, 1952);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Franklin Roosevelt', 'Harry Truman', 1944, 1948);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Thomas E. Dewey', 'John W. Bricker', 1944, 1948);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Franklin Roosevelt', 'Henry Wallace', 1940, 1944);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Wendell Willkie', 'Charles L. McNary', 1940, 1944);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Franklin Roosevelt', 'John Garner', 1936, 1940);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Alf Landon', 'Frank Knox', 1936, 1940);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Franklin Roosevelt', 'John Garner', 1932, 1936);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Herbert Hoover', 'Charles Curtis', 1932, 1936);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Herbert Hoover', 'Charles Curtis', 1928, 1932);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Al Smith', 'Joseph Robinson', 1928, 1932);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Calvin Coolidge', 'Charles G. Dawes', 1924, 1928);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John W. Davis', 'Charles W. Bryan', 1924, 1928);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Robert La Follette', 'Burton K. Wheeler', 1924, 1928);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Warren Harding', 'Calvin Coolidge', 1920, 1924);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James M. Cox', 'Franklin Roosevelt', 1920, 1924);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Woodrow Wilson', 'Thomas R. Marshall', 1916, 1920);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Charles Evans Hughes', 'Charles W. Fairbanks', 1916, 1920);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Woodrow Wilson', 'Thomas R. Marshall', 1912, 1916);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Theodore Roosevelt', 'Hiram Johnson', 1912, 1916);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('William Howard Taft', 'James S. Sherman', 1912, 1916);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('William Howard Taft', 'James S. Sherman', 1908, 1912);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('William Jennings Bryan', 'John W. Kern', 1908, 1912);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Theodore Roosevelt', 'Charles W. Fairbanks', 1904, 1908);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Alton B. Parker', 'Henry G. Davis', 1904, 1908);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('William McKinley', 'Theodore Roosevelt', 1900, 1904);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('William Jennings Bryan', 'Adlai Stevenson I', 1900, 1904);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('William McKinley', 'Garret Hobart', 1896, 1900);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('William Jennings Bryan', 'Arthur Sewall', 1896, 1900);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Grover Cleveland', 'Adlai Stevenson I', 1892, 1896);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Benjamin Harrison', 'Whitelaw Reid', 1892, 1896);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Benjamin Harrison', 'Levi P. Morton', 1888, 1892);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Grover Cleveland', 'Allen G. Thurman', 1888, 1892);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Grover Cleveland', 'Thomas A. Hendricks', 1884, 1888);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James G. Blaine', 'John A. Logan', 1884, 1888);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James A. Garfield', 'Chester A. Arthur', 1880, 1884);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Winfield S. Hancock', 'William English', 1880, 1884);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Rutherford B. Hayes', 'William A. Wheeler', 1876, 1880);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Samuel Tilden', 'Thomas A. Hendricks', 1876, 1880);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Ulysses S. Grant', 'Henry Wilson', 1872, 1876);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Horace Greeley', 'Benjamin G. Brown', 1872, 1876);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Ulysses S. Grant', 'Schuyler Colfax', 1868, 1872);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Horatio Seymour', 'Francis Blair', 1868, 1872);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Abraham Lincoln', 'Andrew Johnson', 1864, 1868);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('George B. McClellan', 'George H. Pendleton', 1864, 1868);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Abraham Lincoln', 'Hannibal Hamlin', 1860, 1864);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John C. Breckinridge', 'Joseph Lane', 1860, 1864);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John Bell', 'Edward Everett', 1860, 1864);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Stephen A. Douglas', 'Herschel V. Johnson', 1860, 1864);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James Buchanan', 'John C. Breckinridge', 1856, 1860);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John C. Fremont', 'William L. Dayton', 1856, 1860);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Millard Fillmore', 'Andrew J. Donelson', 1856, 1860);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Franklin Pierce', 'William R. King', 1852, 1856);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Winfield Scott', 'William A. Graham', 1852, 1856);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Zachary Taylor', 'Millard Fillmore', 1848, 1852);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Lewis Cass', 'William Butler', 1848, 1852);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Martin Van Buren', 'Charles F. Adams', 1848, 1852);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James K. Polk', 'George M. Dallas', 1844, 1848);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Henry Clay', 'Theodore Frelinghuysen', 1844, 1848);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('William Henry Harrison', 'John Tyler', 1840, 1844);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Martin Van Buren', 'None', 1840, 1844);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Martin Van Buren', 'Richard Johnson', 1836, 1840);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('William Henry Harrison', 'Francis Granger', 1836, 1840);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Andrew Jackson', 'Martin Van Buren', 1832, 1836);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Henry Clay', 'John Sergeant', 1832, 1836);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Andrew Jackson', 'John C. Calhoun', 1828, 1832);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John Quincy Adams', 'Richard Rush', 1828, 1832);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John Quincy Adams', 'John C. Calhoun', 1824, 1828);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Andrew Jackson', 'John C. Calhoun', 1824, 1828);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('William H. Crawford', 'Nathaniel Macon', 1824, 1828);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Henry Clay', 'Nathan Sanford', 1824, 1828);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James Monroe', 'Daniel D. Tompkins', 1820, 1824);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James Monroe', 'Daniel D. Tompkins', 1816, 1820);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Rufus King', 'John Howard', 1816, 1820);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James Madison', 'Elbridge Gerry', 1812, 1816);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('DeWitt Clinton', 'Jared Ingersoll', 1812, 1816);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James Madison', 'George Clinton', 1808, 1812);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Charles Pinckney', 'Rufus King', 1808, 1812);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Thomas Jefferson', 'George Clinton', 1804, 1808);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Charles Pinckney', 'Rufus King', 1804, 1808);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Thomas Jefferson', 'Aaron Burr', 1800, 1804);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John Adams', 'Charles Pinckney', 1800, 1804);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John Adams', 'Thomas Pinckney', 1796, 1800);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Thomas Jefferson', 'Aaron Burr', 1796, 1800);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('George Washington', 'John Adams', 1792, 1796);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('George Washington', 'John Adams', 1789, 1793);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Gary Johnson', 'William Weld', 2016, 2020);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Jill Stein', 'Ajamu Baraka', 2016, 2020);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Ralph Nader', 'Winona LaDuke', 2000, 2004);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Ross Perot', 'Pat Choate', 1996, 2000);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John B. Anderson', 'Patrick Lucey', 1980, 1984);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Ed Clark', 'David Koch', 1980, 1984);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John G. Schmitz', 'Thomas J. Anderson', 1972, 1976);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Harry F. Byrd', 'Strom Thurmond', 1960, 1964);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Strom Thurmond', 'Fielding L. Wright', 1948, 1952);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Henry A. Wallace', 'Glen H. Taylor', 1948, 1952);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('William Lemke', 'Thomas C. OBrien', 1936, 1940);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Norman Thomas', 'James H. Maurer', 1932, 1936);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Eugene V. Debs', 'Seymour Stedman', 1920, 1924);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Allan L. Benson', 'George Kirkpatrick', 1916, 1920);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Frank Hanly', 'Ira Landrith', 1916, 1920);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Eugene V. Debs', 'Emil Seidel', 1912, 1916);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Eugene W. Chafin', 'Aaron S. Watkins', 1912, 1916);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Eugene V. Debs', 'Ben Hanford', 1908, 1912);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Eugene W. Chafin', 'Aaron S. Watkins', 1908, 1912);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Eugene V. Debs', 'Ben Hanford', 1904, 1908);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Silas C. Swallow', 'George W. Carroll', 1904, 1908);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John G. Woolley', 'Henry B. Metcalf', 1900, 1904);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James B. Weaver', 'James G. Field', 1892, 1896);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John Bidwell', 'James B. Cranfill', 1892, 1896);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Clinton B. Fisk', 'John A. Brooks', 1888, 1892);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Alson Streeter', 'Charles Cunningham', 1888, 1892);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Benjamin F. Butler', 'Absolom M. West', 1884, 1888);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John St. John', 'William Daniel', 1884, 1888);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James B. Weaver', 'Barzillai Chambers', 1880, 1884);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John P. Hale', 'George W. Julian', 1852, 1856);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James G. Birney', 'Thomas Morris', 1844, 1848);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Hugh Lawson White', 'John Tyler', 1836, 1840);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Daniel Webster', 'Francis Granger', 1836, 1840);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Willie Mangum', 'John Tyler', 1836, 1840);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('John Floyd', 'Henry Lee', 1832, 1836);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('William Wirt', 'Amos Ellmaker', 1832, 1836);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('Rufus King', 'William Davie', 1812, 1816);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('George Clinton', 'James Monroe', 1808, 1812);
insert into db.RUNNING_MATE (cName, rName, StartYear, EndYear) values ('James Monroe', 'None', 1808, 1812);

select * from RUNNING_MATE;