delete from db.PRESIDENT;

insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('George Washington', 1789, 1793, 'washington');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('George Washington', 1792, 1796, 'washington');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('John Adams', 1796, 1800, 'Adams');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('Thomas Jefferson', 1800, 1804, 'Jefferson');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('Thomas Jefferson', 1804, 1808, 'Jefferson');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('James Madison', 1808, 1812, 'Madison');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('James Madison', 1812, 1816, 'Madison');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('James Monroe', 1816, 1820, 'Monroe');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('James Monroe', 1820, 1824, 'Monroe');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('JOHN Q. ADAMS', 1824, 1828, 'JQAdams');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('ANDREW JACKSON', 1828, 1832, 'Jackson');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('ANDREW JACKSON', 1832, 1836, 'Jackson');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('MARTIN VAN BUREN', 1836, 1840, 'VanBuren');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('WILLIAM H. HARRISON', 1840, 1841, 'WilliamHarrison');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('JOHN TYLER', 1841, 1844, 'Tyler');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('JAMES K. POLK', 1844, 1848, 'Polk');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('ZACHARY TAYLOR', 1848, 1850, 'Taylor');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('MILLARD FILLMORE', 1850, 1852, 'Fillmore');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('FRANKLIN PIERCE', 1852, 1856, 'Pierce');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('JAMES BUCHANAN', 1856, 1860, 'Buchanan');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('ABRAHAM LINCOLN', 1860, 1864, 'Lincoln');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('ABRAHAM LINCOLN', 1864, 1865, 'Lincoln');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('ANDREW JOHNSON', 1865, 1868, 'Johnson');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('ULYSSES S. GRANT', 1868, 1872, 'Grant');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('ULYSSES S. GRANT', 1872, 1876, 'Grant');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('RUTHERFORD B. HAYES', 1876, 1880, 'Hayes');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('JAMES A. GARFIELD', 1880, 1881, 'Garfield');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('CHESTER ARTHUR', 1881, 1884, 'Arthur');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('GROVER CLEVELAND', 1884, 1888, 'Cleveland');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('BENJAMIN HARRISON', 1888, 1892, 'BenHarrison');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('GROVER CLEVELAND', 1892, 1896, 'Cleveland');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('WILLIAM McKINLEY', 1896, 1900, 'McKinley');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('WILLIAM McKINLEY', 1900, 1901, 'McKinley');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('THEODORE ROOSEVELT', 1901, 1904, 'TeddyRoosevelt');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('THEODORE ROOSEVELT', 1904, 1908, 'TeddyRoosevelt');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('WILLIAM H. TAFT', 1908, 1912, 'Taft');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('WOODROW WILSON', 1912, 1916, 'Wilson');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('WOODROW WILSON', 1916, 1920, 'Wilson');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('WARREN G. HARDING', 1920, 1923, 'Harding');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('CALVIN COOLIDGE', 1923, 1924, 'Coolidge');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('CALVIN COOLIDGE', 1924, 1928, 'Coolidge');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('HERBERT HOOVER', 1928, 1932, 'Hoover');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('FRANKLIN D. ROOSEVELT', 1932, 1936, 'FDR');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('FRANKLIN D. ROOSEVELT', 1936, 1940, 'FDR');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('FRANKLIN D. ROOSEVELT', 1940, 1944, 'FDR');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('HARRY S TRUMAN', 1944, 1958, 'Truman');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('HARRY S TRUMAN', 1948, 1952, 'Truman');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('DWIGHT D. EISENHOWER', 1952, 1956, 'Eisenhower');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('DWIGHT D. EISENHOWER', 1956, 1960, 'Eisenhower');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('JOHN F. KENNEDY', 1960, 1963, 'JFK');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('LYNDON B. JOHNSON', 1963, 1964, 'LBJ');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('LYNDON B. JOHNSON', 1964, 1968, 'LBJ');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('RICHARD M. NIXON', 1968, 1972, 'Nixon');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('RICHARD M. NIXON', 1972, 1974, 'Nixon');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('GERALD FORD', 1974, 1976, 'Ford');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('JIMMY CARTER', 1976, 1980, 'Carter');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('RONALD REAGAN', 1980, 1984, 'Reagan');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('RONALD REAGAN', 1984, 1988, 'Reagan');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('GEORGE BUSH', 1988, 1992, 'GeorgeHWBush');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('BILL CLINTON', 1992, 1996, 'Clinton');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('BILL CLINTON', 1996, 2000, 'Clinton');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('GEORGE W. BUSH', 2000, 2004, 'GeorgeWBush');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('GEORGE W. BUSH', 2004, 2008, 'GeorgeWBush');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('BARACK OBAMA', 2008, 2012, 'Obama');
insert into db.PRESIDENT (Name, StartYear, EndYear, Picture) values ('BARACK OBAMA', 2012, 2016, 'Obama');

select * from db.PRESIDENT;